builds:
  - binary: nepcal
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/nepcal

archive:
  format: tar.gz

brew:
  name: nepcal
  github:
    owner: srishanbhattarai
    name: nepcal
  folder: Formula
  homepage: https://github.com/nepcal/nepcal
  description: Equivalent of Linux's cal, for Nepali dates
